/**
 * Single source of truth for geo market definitions and discovery anchors.
 * Rows in public.markets mirror this registry (migration 012).
 */

export type MarketDefinition = {
  slug: string;
  displayName: string;
  centerLat: number;
  centerLng: number;
  radiusMiles: number;
  /** Outdoorsy search address; null = display-only (fed by overlapping discovery). */
  outdoorsyAddress: string | null;
  /** RVshare location string; null = display-only. */
  rvshareLocation: string | null;
  region: string;
  sortOrder: number;
  isLive: boolean;
};

export const MARKETS: MarketDefinition[] = [
  {
    slug: "san-diego-ca",
    displayName: "San Diego, CA",
    centerLat: 32.7157,
    centerLng: -117.1611,
    radiusMiles: 35,
    outdoorsyAddress: "San Diego, CA",
    rvshareLocation: "san diego ca",
    region: "California",
    sortOrder: 10,
    isLive: true,
  },
  {
    slug: "riverside-county-ca",
    displayName: "Riverside County, CA",
    centerLat: 33.9533,
    centerLng: -117.3962,
    radiusMiles: 45,
    outdoorsyAddress: "Riverside County, CA",
    rvshareLocation: "riverside county ca",
    region: "California",
    sortOrder: 20,
    isLive: true,
  },
  {
    slug: "portland-or",
    displayName: "Portland, OR",
    centerLat: 45.5152,
    centerLng: -122.6784,
    radiusMiles: 35,
    outdoorsyAddress: "Portland, OR",
    rvshareLocation: "portland or",
    region: "Pacific Northwest",
    sortOrder: 30,
    isLive: true,
  },
  {
    slug: "arklatex",
    displayName: "ArkLaTex",
    centerLat: 32.5252,
    centerLng: -93.7502,
    radiusMiles: 50,
    outdoorsyAddress: "Shreveport, LA",
    rvshareLocation: "shreveport la",
    region: "Southwest",
    sortOrder: 40,
    isLive: true,
  },
  {
    slug: "los-angeles-ca",
    displayName: "Los Angeles, CA",
    centerLat: 34.0522,
    centerLng: -118.2437,
    radiusMiles: 40,
    outdoorsyAddress: "Los Angeles, CA",
    rvshareLocation: "los angeles ca",
    region: "California",
    sortOrder: 50,
    isLive: true,
  },
  {
    slug: "orange-county-ca",
    displayName: "Orange County, CA",
    centerLat: 33.7175,
    centerLng: -117.8311,
    radiusMiles: 30,
    outdoorsyAddress: "Orange County, CA",
    rvshareLocation: "orange county ca",
    region: "California",
    sortOrder: 52,
    isLive: true,
  },
  {
    slug: "long-beach-ca",
    displayName: "Long Beach, CA",
    centerLat: 33.7701,
    centerLng: -118.1937,
    radiusMiles: 25,
    outdoorsyAddress: null,
    rvshareLocation: null,
    region: "California",
    sortOrder: 55,
    isLive: true,
  },
  {
    slug: "sacramento-ca",
    displayName: "Sacramento, CA",
    centerLat: 38.5816,
    centerLng: -121.4944,
    radiusMiles: 35,
    outdoorsyAddress: "Sacramento, CA",
    rvshareLocation: "sacramento ca",
    region: "California",
    sortOrder: 60,
    isLive: true,
  },
  {
    slug: "san-francisco-ca",
    displayName: "San Francisco, CA",
    centerLat: 37.7749,
    centerLng: -122.4194,
    radiusMiles: 35,
    outdoorsyAddress: "San Francisco, CA",
    rvshareLocation: "san francisco ca",
    region: "California",
    sortOrder: 70,
    isLive: true,
  },
  {
    slug: "san-jose-ca",
    displayName: "San Jose, CA",
    centerLat: 37.3382,
    centerLng: -121.8863,
    radiusMiles: 30,
    outdoorsyAddress: null,
    rvshareLocation: null,
    region: "California",
    sortOrder: 75,
    isLive: true,
  },
  {
    slug: "denver-co",
    displayName: "Denver, CO",
    centerLat: 39.7392,
    centerLng: -104.9903,
    radiusMiles: 40,
    outdoorsyAddress: "Denver, CO",
    rvshareLocation: "denver co",
    region: "Mountain West",
    sortOrder: 100,
    isLive: true,
  },
  {
    slug: "salt-lake-city-ut",
    displayName: "Salt Lake City, UT",
    centerLat: 40.7608,
    centerLng: -111.891,
    radiusMiles: 35,
    outdoorsyAddress: "Salt Lake City, UT",
    rvshareLocation: "salt lake city ut",
    region: "Mountain West",
    sortOrder: 110,
    isLive: true,
  },
  {
    slug: "reno-nv",
    displayName: "Reno, NV",
    centerLat: 39.5296,
    centerLng: -119.8138,
    radiusMiles: 35,
    outdoorsyAddress: "Reno, NV",
    rvshareLocation: "reno nv",
    region: "Mountain West",
    sortOrder: 120,
    isLive: true,
  },
  {
    slug: "cheyenne-wy",
    displayName: "Cheyenne, WY",
    centerLat: 41.14,
    centerLng: -104.8202,
    radiusMiles: 40,
    outdoorsyAddress: "Cheyenne, WY",
    rvshareLocation: "cheyenne wy",
    region: "Mountain West",
    sortOrder: 130,
    isLive: true,
  },
  {
    slug: "phoenix-az",
    displayName: "Phoenix, AZ",
    centerLat: 33.4484,
    centerLng: -112.074,
    radiusMiles: 45,
    outdoorsyAddress: "Phoenix, AZ",
    rvshareLocation: "phoenix az",
    region: "Southwest",
    sortOrder: 200,
    isLive: true,
  },
  {
    slug: "austin-tx",
    displayName: "Austin, TX",
    centerLat: 30.2672,
    centerLng: -97.7431,
    radiusMiles: 35,
    outdoorsyAddress: "Austin, TX",
    rvshareLocation: "austin tx",
    region: "Southwest",
    sortOrder: 210,
    isLive: true,
  },
  {
    slug: "san-antonio-tx",
    displayName: "San Antonio, TX",
    centerLat: 29.4241,
    centerLng: -98.4936,
    radiusMiles: 35,
    outdoorsyAddress: "San Antonio, TX",
    rvshareLocation: "san antonio tx",
    region: "Southwest",
    sortOrder: 220,
    isLive: true,
  },
  {
    slug: "dallas-fort-worth-tx",
    displayName: "Dallas / Fort Worth, TX",
    centerLat: 32.7767,
    centerLng: -96.797,
    radiusMiles: 45,
    outdoorsyAddress: "Dallas, TX",
    rvshareLocation: "dallas tx",
    region: "Southwest",
    sortOrder: 230,
    isLive: true,
  },
  {
    slug: "albuquerque-nm",
    displayName: "Albuquerque, NM",
    centerLat: 35.0844,
    centerLng: -106.6504,
    radiusMiles: 35,
    outdoorsyAddress: "Albuquerque, NM",
    rvshareLocation: "albuquerque nm",
    region: "Southwest",
    sortOrder: 240,
    isLive: true,
  },
  {
    slug: "orlando-fl",
    displayName: "Orlando, FL",
    centerLat: 28.5383,
    centerLng: -81.3792,
    radiusMiles: 35,
    outdoorsyAddress: "Orlando, FL",
    rvshareLocation: "orlando fl",
    region: "Southeast",
    sortOrder: 300,
    isLive: true,
  },
  {
    slug: "tampa-fl",
    displayName: "Tampa, FL",
    centerLat: 27.9506,
    centerLng: -82.4572,
    radiusMiles: 35,
    outdoorsyAddress: "Tampa, FL",
    rvshareLocation: "tampa fl",
    region: "Southeast",
    sortOrder: 310,
    isLive: true,
  },
  {
    slug: "atlanta-ga",
    displayName: "Atlanta, GA",
    centerLat: 33.749,
    centerLng: -84.388,
    radiusMiles: 40,
    outdoorsyAddress: "Atlanta, GA",
    rvshareLocation: "atlanta ga",
    region: "Southeast",
    sortOrder: 320,
    isLive: true,
  },
  {
    slug: "chattanooga-tn",
    displayName: "Chattanooga, TN",
    centerLat: 35.0456,
    centerLng: -85.3097,
    radiusMiles: 30,
    outdoorsyAddress: "Chattanooga, TN",
    rvshareLocation: "chattanooga tn",
    region: "Southeast",
    sortOrder: 330,
    isLive: true,
  },
  {
    slug: "jacksonville-fl",
    displayName: "Jacksonville, FL",
    centerLat: 30.3322,
    centerLng: -81.6557,
    radiusMiles: 35,
    outdoorsyAddress: "Jacksonville, FL",
    rvshareLocation: "jacksonville fl",
    region: "Southeast",
    sortOrder: 340,
    isLive: true,
  },
  {
    slug: "columbus-oh",
    displayName: "Columbus, OH",
    centerLat: 39.9612,
    centerLng: -82.9988,
    radiusMiles: 35,
    outdoorsyAddress: "Columbus, OH",
    rvshareLocation: "columbus oh",
    region: "Midwest",
    sortOrder: 400,
    isLive: true,
  },
  {
    slug: "cincinnati-oh",
    displayName: "Cincinnati, OH",
    centerLat: 39.1031,
    centerLng: -84.512,
    radiusMiles: 35,
    outdoorsyAddress: "Cincinnati, OH",
    rvshareLocation: "cincinnati oh",
    region: "Midwest",
    sortOrder: 410,
    isLive: true,
  },
  {
    slug: "detroit-mi",
    displayName: "Detroit, MI",
    centerLat: 42.3314,
    centerLng: -83.0458,
    radiusMiles: 35,
    outdoorsyAddress: "Detroit, MI",
    rvshareLocation: "detroit mi",
    region: "Midwest",
    sortOrder: 420,
    isLive: true,
  },
  {
    slug: "grand-rapids-mi",
    displayName: "Grand Rapids, MI",
    centerLat: 42.9634,
    centerLng: -85.6681,
    radiusMiles: 30,
    outdoorsyAddress: "Grand Rapids, MI",
    rvshareLocation: "grand rapids mi",
    region: "Midwest",
    sortOrder: 430,
    isLive: true,
  },
  {
    slug: "madison-wi",
    displayName: "Madison, WI",
    centerLat: 43.0731,
    centerLng: -89.4012,
    radiusMiles: 30,
    outdoorsyAddress: "Madison, WI",
    rvshareLocation: "madison wi",
    region: "Midwest",
    sortOrder: 440,
    isLive: true,
  },
  {
    slug: "milwaukee-wi",
    displayName: "Milwaukee, WI",
    centerLat: 43.0389,
    centerLng: -87.9065,
    radiusMiles: 35,
    outdoorsyAddress: "Milwaukee, WI",
    rvshareLocation: "milwaukee wi",
    region: "Midwest",
    sortOrder: 450,
    isLive: true,
  },
  {
    slug: "minneapolis-mn",
    displayName: "Minneapolis, MN",
    centerLat: 44.9778,
    centerLng: -93.265,
    radiusMiles: 40,
    outdoorsyAddress: "Minneapolis, MN",
    rvshareLocation: "minneapolis mn",
    region: "Midwest",
    sortOrder: 460,
    isLive: true,
  },
  {
    slug: "philadelphia-pa",
    displayName: "Philadelphia, PA",
    centerLat: 39.9526,
    centerLng: -75.1652,
    radiusMiles: 35,
    outdoorsyAddress: "Philadelphia, PA",
    rvshareLocation: "philadelphia pa",
    region: "Northeast",
    sortOrder: 500,
    isLive: true,
  },
  {
    slug: "baltimore-md",
    displayName: "Baltimore, MD",
    centerLat: 39.2904,
    centerLng: -76.6122,
    radiusMiles: 30,
    outdoorsyAddress: "Baltimore, MD",
    rvshareLocation: "baltimore md",
    region: "Northeast",
    sortOrder: 510,
    isLive: true,
  },
  {
    slug: "new-york-ny",
    displayName: "New York, NY",
    centerLat: 40.7128,
    centerLng: -74.006,
    radiusMiles: 35,
    outdoorsyAddress: "New York, NY",
    rvshareLocation: "new york ny",
    region: "Northeast",
    sortOrder: 520,
    isLive: true,
  },
  {
    slug: "washington-dc",
    displayName: "Washington, DC",
    centerLat: 38.9072,
    centerLng: -77.0369,
    radiusMiles: 35,
    outdoorsyAddress: "Washington, DC",
    rvshareLocation: "washington dc",
    region: "Northeast",
    sortOrder: 530,
    isLive: true,
  },
  {
    slug: "harrisburg-pa",
    displayName: "Harrisburg, PA",
    centerLat: 40.2732,
    centerLng: -76.8867,
    radiusMiles: 30,
    outdoorsyAddress: "Harrisburg, PA",
    rvshareLocation: "harrisburg pa",
    region: "Northeast",
    sortOrder: 540,
    isLive: true,
  },
  {
    slug: "hartford-ct",
    displayName: "Hartford, CT",
    centerLat: 41.7658,
    centerLng: -72.6734,
    radiusMiles: 35,
    outdoorsyAddress: "Hartford, CT",
    rvshareLocation: "hartford ct",
    region: "Northeast",
    sortOrder: 550,
    isLive: true,
  },
  {
    slug: "richmond-va",
    displayName: "Richmond, VA",
    centerLat: 37.5407,
    centerLng: -77.436,
    radiusMiles: 35,
    outdoorsyAddress: "Richmond, VA",
    rvshareLocation: "richmond va",
    region: "Northeast",
    sortOrder: 560,
    isLive: true,
  },
  {
    slug: "seattle-wa",
    displayName: "Seattle, WA",
    centerLat: 47.6062,
    centerLng: -122.3321,
    radiusMiles: 35,
    outdoorsyAddress: "Seattle, WA",
    rvshareLocation: "seattle wa",
    region: "Pacific Northwest",
    sortOrder: 600,
    isLive: true,
  },
];

export const MARKET_BY_SLUG = Object.fromEntries(MARKETS.map((m) => [m.slug, m])) as Record<
  string,
  MarketDefinition
>;

export function discoveryMarkets(): MarketDefinition[] {
  return MARKETS.filter((m) => m.isLive && m.outdoorsyAddress && m.rvshareLocation);
}

export function marketDisplayName(slug: string): string {
  return MARKET_BY_SLUG[slug]?.displayName ?? slug;
}

export function liveMarkets(): MarketDefinition[] {
  return MARKETS.filter((m) => m.isLive).sort((a, b) => a.sortOrder - b.sortOrder);
}
